- hosts: local
  become: true

  tasks:
    - lineinfile:
        path: /usr/share/palamar/palamar/palamar/settings.py
        regexp: '^SITE_ROOT_URL'
        line: 'SITE_ROOT_URL = "http://demo.dash-stack.com"'

    - lineinfile:
        path: /usr/share/palamar/palamar/palamar/settings.py
        regexp: '^STATICFILES_DIRS'
        state: absent

    - lineinfile:
        path: /usr/share/palamar/palamar/palamar/settings.py
        line: 'STATIC_ROOT = "static"'

    - template:
        src: /usr/share/palamar/palamar/conf/local_settings.py.template
        dest: /usr/share/palamar/palamar/palamar/local_settings.py
        owner: jenkins
        group: jenkins
